version: '3.8'

services:
  gen-ai-tester:
    build: .
    container_name: api-tester-ai
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - target-microservice
    networks:
      - app-network

  target-microservice:
    image: kennethreitz/httpbin
    container_name: target-microservice
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge