services:
  test-api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - target-microservice

  target-microservice:
    image: genaitester:latest
    ports:
      - "8081:8081"